vaadin.launch-browser=true
spring.application.name=myDesk
spring.datasource.url=jdbc:postgresql://localhost:5432/myDesk
spring.datasource.username=postgres
spring.datasource.password=RollingThunder1975
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration